#!/usr/bin/env python3

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = ROOT / "knowledge" / "topic-registry.yaml"
CONCEPT_MAP_PATH = ROOT / "knowledge" / "concept-map.md"

LEVEL_ORDER = ["A1", "A2", "B1", "B2", "C1", "C2"]
LEVEL_LABELS = {
    "A1": "Absolute Beginner",
    "A2": "Elementary",
    "B1": "Intermediate",
    "B2": "Upper Intermediate",
    "C1": "Advanced",
    "C2": "Near-Native",
}


def parse_registry(path: Path) -> list[dict[str, object]]:
    topics: list[dict[str, object]] = []
    current: dict[str, object] | None = None
    active_list: str | None = None

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue

        if raw_line.startswith("  - id: "):
            if current is not None:
                topics.append(current)
            current = {
                "id": raw_line.split(": ", 1)[1].strip(),
                "prereqs": [],
                "next_topics": [],
            }
            active_list = None
            continue

        if current is None:
            continue

        line = raw_line.rstrip()
        stripped = line.strip()

        if line.startswith("    level: "):
            current["level"] = stripped.split(": ", 1)[1]
        elif line.startswith("    path: "):
            current["path"] = stripped.split(": ", 1)[1]
        elif line.startswith("    prereqs: []"):
            current["prereqs"] = []
            active_list = None
        elif line.startswith("    prereqs:"):
            current["prereqs"] = []
            active_list = "prereqs"
        elif line.startswith("    next_topics: []"):
            current["next_topics"] = []
            active_list = None
        elif line.startswith("    next_topics:"):
            current["next_topics"] = []
            active_list = "next_topics"
        elif line.startswith("      - "):
            if active_list in {"prereqs", "next_topics"}:
                current[active_list].append(stripped[2:].strip())
        else:
            active_list = None

    if current is not None:
        topics.append(current)

    missing = [topic["id"] for topic in topics if "level" not in topic or "path" not in topic]
    if missing:
        raise ValueError(f"Registry entries missing required fields: {', '.join(str(item) for item in missing)}")

    return topics


def extract_objective(path: Path) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"^## Objective\s*\n(.+?)(?:\n\s*\n|\n## )", text, re.MULTILINE | re.DOTALL)
    if not match:
        raise ValueError(f"Missing objective section in {path}")
    objective = " ".join(line.strip() for line in match.group(1).splitlines() if line.strip())
    objective = re.sub(r"\s+", " ", objective).strip()
    return objective


def make_summary(objective: str) -> str:
    if re.search(r'[.!?]["\']?$', objective):
        return objective
    return objective + "."


def render_concept_map(topics: list[dict[str, object]]) -> str:
    grouped: dict[str, list[dict[str, object]]] = {level: [] for level in LEVEL_ORDER}
    for topic in topics:
        grouped[str(topic["level"])].append(topic)

    lines: list[str] = [
        "<!-- Generated by scripts/generate-concept-map.py. Do not edit manually. -->",
        "# Concept Map (English)",
        "",
        "Human-readable curriculum overview generated from `knowledge/topic-registry.yaml`. Edit the registry, then regenerate this file.",
        "",
        "---",
    ]

    for level in LEVEL_ORDER:
        entries = grouped[level]
        if not entries:
            continue

        lines.extend(["", f"## {level} - {LEVEL_LABELS[level]}", ""])
        for topic in entries:
            prereqs = topic["prereqs"]
            prereq_text = ", ".join(str(item) for item in prereqs) if prereqs else ""
            topic_path = Path(str(topic["path"]))
            relative_topic_path = topic_path.as_posix().removeprefix("knowledge/")
            objective = extract_objective(ROOT / topic_path)
            summary = make_summary(objective)

            lines.append(
                f"- **{topic['id']}**: prereqs=[{prereq_text}] -> `{relative_topic_path}`"
            )
            lines.append(f"  {summary}")
            lines.append("")

        if lines[-1] == "":
            lines.pop()

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate knowledge/concept-map.md from knowledge/topic-registry.yaml.")
    parser.add_argument("--check", action="store_true", help="Exit non-zero if concept-map.md is out of date.")
    parser.add_argument("--stdout", action="store_true", help="Print the generated content instead of writing it.")
    args = parser.parse_args()

    topics = parse_registry(REGISTRY_PATH)
    rendered = render_concept_map(topics)

    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    if args.check:
        current = CONCEPT_MAP_PATH.read_text(encoding="utf-8")
        if current != rendered:
            diff = difflib.unified_diff(
                current.splitlines(),
                rendered.splitlines(),
                fromfile=str(CONCEPT_MAP_PATH),
                tofile="generated concept map",
                lineterm="",
            )
            for line in diff:
                print(line)
            return 1
        return 0

    CONCEPT_MAP_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
