#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
failures=0

check_file() {
  local rel="$1"
  if [[ ! -f "$ROOT/$rel" ]]; then
    printf 'FAIL missing file: %s\n' "$rel"
    failures=1
  fi
}

check_contains() {
  local rel="$1"
  local pattern="$2"
  local description="$3"
  if ! grep -Eq "$pattern" "$ROOT/$rel"; then
    printf 'FAIL %s: %s\n' "$description" "$rel"
    failures=1
  fi
}

required_files=(
  "README.md"
  "RULES.md"
  "AGENT.md"
  "SOUL.md"
  "LEARNER.md"
  "memory/MEMORY.md"
  "memory/sessions/_template.md"
  ".agent/workflows/english.md"
  "knowledge/concept-map.md"
  "knowledge/topic-registry.yaml"
  "CLAUDE.md"
  "GEMINI.md"
  "qa/behavior-regressions.md"
  "scripts/generate-concept-map.py"
  "scripts/run-gemini-regressions.sh"
)

for rel in "${required_files[@]}"; do
  check_file "$rel"
done

check_contains "AGENT.md" "RULES\\.md" "AGENT should point to hard rules"
check_contains "CLAUDE.md" "RULES\\.md" "CLAUDE entry should load hard rules"
check_contains "GEMINI.md" "RULES\\.md" "GEMINI entry should load hard rules"
check_contains ".agent/workflows/english.md" "RULES\\.md" "workflow should load hard rules"
check_contains "knowledge/concept-map.md" "Generated by scripts/generate-concept-map\\.py" "concept map should be generated"

check_contains "LEARNER.md" "^## Stable Identity$" "LEARNER should use durable-profile sections"
check_contains "memory/MEMORY.md" "^## Current Focus$" "MEMORY should track live focus"
check_contains "memory/MEMORY.md" "^## Recommended Next Drill$" "MEMORY should track next drill"

if grep -Eq "^## Concepts: Solid$|^## Concepts: Shaky$|^## Error Fingerprint$" "$ROOT/LEARNER.md"; then
  printf 'FAIL LEARNER contains live mastery headings that belong in memory/MEMORY.md\n'
  failures=1
fi

topic_file_count="$(find "$ROOT/knowledge/topics" -maxdepth 1 -type f -name '*.md' | wc -l | tr -d ' ')"
registry_count="$(grep -c '^  - id:' "$ROOT/knowledge/topic-registry.yaml" || true)"
if [[ "$topic_file_count" != "$registry_count" ]]; then
  printf 'FAIL topic count mismatch: registry=%s topics=%s\n' "$registry_count" "$topic_file_count"
  failures=1
fi

while IFS= read -r rel_path; do
  [[ -z "$rel_path" ]] && continue
  if [[ ! -f "$ROOT/$rel_path" ]]; then
    printf 'FAIL registry path missing: %s\n' "$rel_path"
    failures=1
  fi
done < <(sed -n 's/^    path: //p' "$ROOT/knowledge/topic-registry.yaml")

while IFS= read -r filename; do
  [[ "$filename" == "_template.md" ]] && continue
  if [[ ! "$filename" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}\.md$ ]]; then
    printf 'FAIL invalid session filename: %s\n' "$filename"
    failures=1
  fi
done < <(find "$ROOT/memory/sessions" -maxdepth 1 -type f -printf '%f\n' | sort)

concept_map_check_output="$(mktemp)"
if ! python3 "$ROOT/scripts/generate-concept-map.py" --check >"$concept_map_check_output" 2>&1; then
  cat "$concept_map_check_output"
  printf 'FAIL concept map is out of date. Regenerate with python3 scripts/generate-concept-map.py\n'
  rm -f "$concept_map_check_output"
  failures=1
else
  rm -f "$concept_map_check_output"
fi

if [[ "$failures" -ne 0 ]]; then
  exit 1
fi

printf 'Workspace validation passed.\n'
